### ISSUE TITLE
arxiv2bib not working with 2015 arXiv ids?

### ISSUE THREAD

**Issue by yosefrajwulf** [nathangrigg/arxiv2bib#3]
I have tried to fetch the bibtex info for the following arXiv identifiers:
1504.00233v1
1502.02086v1
1503.04448v1
and I get the following error for each of them
"Error: Invalid arXiv identifier"
"No succesful matches"

**Comment by nathangrigg** [comment]
This should be fixed by 10e83e5 which was released in version 1.0.6. 

Could you make sure you have the newest version installed and let me know if this is still a problem?

**Comment by yosefrajwulf** [comment]
In the last version provided by pip it does not work. However it does work if I download the latest version from github.
