### ISSUE TITLE
Providing a LICENSE or COPYING file

### ISSUE THREAD

**Issue by Earnestly** [nathangrigg/arxiv2bib#9]
Would be possible for you to provide a `LICENSE` file with the specific BSD license you're using, including your copyright?

**Comment by mcepl** [comment]
It is included directly in [arxiv2bib.py](arxiv2bib.py) and it is [BSD-3-Clause](https://en.wikipedia.org/wiki/BSD_licenses#3-clause).

**Comment by Earnestly** [comment]
Yes, that's the problem

**Comment by Earnestly** [comment]
Yes, that's the problem

**Comment by mcepl** [comment]
Why is it a problem?

**Comment by Earnestly** [comment]
Because it means that one has to carve the license text out of another file using various tooling methods instead of just being able to copy a file over.

**Comment by mcepl** [comment]
Why? Are your packaging guidelines so stupid, that they force to do such useful things?

**Comment by Earnestly** [comment]
You replied to this over three years after it was posted and for quite some time I haven't packaged this project.

Your hostile responses seem unwarrented and I have difficulty understanding why you don't agree that having to employ ad hoc commands to strip a license out of a file, expressed in its comments, in a programmatic manner without accurately parsing the language (which can change) the file is written in, might be suboptimal. I would have expected such an obvious set of pitfalls to be immediately understood.

I'm not entirely sure why you consider providing unique license files is "stupid" or "useless". As the name in the file will be different for all such licenses and so cannot be used generally like the GPL or others.

As for `sed`, I remember using `awk` to handle this case as it provided an easier interface to have a few additional guard rails against the text changing in subtle ways. It was a a fair waste of time and it appears others will be subject to the same issues, along with potentially new avenues for bugs that decisions such as yours can lead to.

**Comment by mcepl** [comment]
> Your hostile responses seem unwarrented and I have difficulty understanding why you don't agree that having to employ ad hoc commands to strip a license out of a file, expressed in its comments, in a programmatic manner without accurately parsing the language (which can change) the file is written in, might be suboptimal.

I don’t like the terms like “hostile” … those imply personal attack, which is something I have never meant. I may have strong opinion sharply expressed, but I was always talking about opinions about ideas not about persons. And if there is anybody who would be guilty in this in my opinion nonsensical rule of need of a license in separate file are Arch Linux leaders, not you.

I mentioned `sed` mainly because the wiki mentioned it.
